### ISSUE TITLE
Get frontend repo ready to utilize material-ui component library

### ISSUE THREAD

**Issue by jhodapp** [Jim-Hodapp-Coaching/refactor-platform-fe#4]
This issue seeks to get this frontend repo ready to utilize [material-ui component library](https://mui.com/material-ui/).

Definition of Done:

- [ ] Can instantiate any Material UI component in this frontend repo

**Comment by naconnors** [comment]
Are you planning on using tailwind styling or just base Material styling? We should remove tailwind dep if not using it.

**Comment by jhodapp** [comment]
Not sure yet, so let's just start by using the default theme of Material UI and leave Tailwind in place. I'm assuming that it's just as easy to remove Tailwind a bit later down the road as it is right now, is that a safe assumption from your experience?

**Comment by jhodapp** [comment]
Actually, now seeing your PR and what was necessary to remove Tailwind, I think that's ok to remove it. It'd be easy enough to bring it back if we want it again.
